server:
  port: 8401
spring:
  application:
    name: hystrix-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
service-url:
  user-service: http://user-service
management:
  endpoints:
    web:
      base-path: actuator
      exposure:
        include: "*" #暴露hystrix监控端点
      cors:
        allowed-origins: true
  server:
    servlet:
      context-path: /